import '../styles/config/import.scss';
import { Montserrat } from 'next/font/google';

export const metadata = {
  title: 'Play X1',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin-ext'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
