import "../styles/config/import.scss";
import { DM_Sans } from "next/font/google";

export const metadata = {
  title: "Play X1",
  description: "Generated by create next app",
};

const Dm_Sans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin-ext"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Dm_Sans.className}>{children}</body>
    </html>
  );
}
